version: '3'
services:
  spring-app:
    container_name: toeicmaster-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=toeic-hero-toeicmaster.e.aivencloud.com
      - DB_PORT=22110
      - DB_USERNAME=avnadmin
      - DB_PASSWORD=AVNS_imM3wBeU7YcBpLLjPe4

